### ISSUE TITLE
Cannot launch proposed Kibana

### ISSUE THREAD

**Issue by remster85** [thecarlo/elastic-kibana-netcore-serilog#1]
Hello, very nice repo and documentation.

When running `docker-compose -up -d` followed by `docker-compose up`, I end up with the message `http server running at http://0:5601"` along with a bunch of warnings.

```
kibana           | {"type":"log","@timestamp":"2020-10-17T03:01:48Z","tags":["reporting","warning"],"pid":6,"message":"Reporting plugin self-check generated a warning: Error: Found 'server.host: \"0\"' in settings. This is incompatible with Reporting. To enable Reporting to work, 'xpack.reporting.kibanaServer.hostname: 0.0.0.0' is being automatically to the configuration. You can change to 'server.host: 0.0.0.0' or add 'xpack.reporting.kibanaServer.hostname: 0.0.0.0' in kibana.yml to prevent this message."}
kibana           | {"type":"log","@timestamp":"2020-10-17T03:01:48Z","tags":["status","plugin:reporting@7.6.2","info"],"pid":6,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
kibana           | {"type":"log","@timestamp":"2020-10-17T03:01:49Z","tags":["listening","info"],"pid":6,"message":"Server running at http://0:5601"}
kibana           | {"type":"log","@timestamp":"2020-10-17T03:01:50Z","tags":["info","http","server","Kibana"],"pid":6,"message":"http server running at http://0:5601"}
```

I am unable to launch kibana :
- http://0:5601
- http://0.0.0.0:5601
- http://localhost:5601

I tried to apply the recommendations `To enable Reporting to work, 'xpack.reporting.kibanaServer.hostname: 0.0.0.0' is being automatically to the configuration. You can change to 'server.host: 0.0.0.0' or add 'xpack.reporting.kibanaServer.hostname: 0.0.0.0' in kibana.yml to prevent this message`.

```
  kibana:
   container_name: kibana
   image: docker.elastic.co/kibana/kibana:7.6.2
   ports:
    - 5601:5601
   depends_on:
    - elasticsearch
   environment:
    - ELASTICSEARCH_URL=http://localhost:9200
    - server.host=0.0.0.0
   networks:
    - elastic

```

or

```
   kibana:
   container_name: kibana
   image: docker.elastic.co/kibana/kibana:7.6.2
   ports:
    - 5601:5601
   depends_on:
    - elasticsearch
   environment:
    - ELASTICSEARCH_URL=http://localhost:9200
    - xpack.reporting.kibanaServer.hostname=0.0.0.0
   networks:
    - elastic
```

but it returns the same warnings than as the first run.

Thanks for your help.
